apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "todo-app.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: {{ .Values.externalSecret.parameterPrefix }}/db-host
    - secretKey: db-port
      remoteRef:
        key: {{ .Values.externalSecret.parameterPrefix }}/db-port
    - secretKey: db-name
      remoteRef:
        key: {{ .Values.externalSecret.parameterPrefix }}/db-name
    - secretKey: db-user
      remoteRef:
        key: {{ .Values.externalSecret.parameterPrefix }}/db-user
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.parameterPrefix }}/db-password
